### PR TITLE
docs: Initial commit to add basic set up tutorial to README.md

### PR DESCRIPTION
**Pull request by jaron-l**
Saw this as low hanging fruit in order to get involved. Trying to address #12 by adding some basic documentation of how to get this extension working.

### CODE REVIEW

**Comment by esteve** [comment]
@jaron-l thanks for your PR, however I'm not sure about the goal of #12 , @bergercookie can you clarify what your request is? The README file for other colcon extension are equally sparse as colcon-cargo's (see https://github.com/colcon/colcon-bazel#readme https://github.com/colcon/colcon-powershell#readme )

**Comment by jaron-l** [comment]
I see that other repositories don't have any documentation but I would think that any documentation is better than no documentation.

I would agree that coming to a consensus on what #12 is referencing would be a great idea.

**Comment by bergercookie** [comment]
Took me a while to answer ^^
The issue I had raised was mainly about adding to the README and demonstrating a way colcon-cargo, what sort of input or file structure it expected and what's the expected results.

To that end, I think @jaron-l 's PR looks good! 
I'll leave a few comments to this but overall

**Comment by bergercookie** [comment]
@jaron-l I've tweaked the README a bit. let me know if you're still happy with it!

**Comment by esteve** [comment]
@bergercookie I've assigned you as a reviewer, if you think the changes are fine and match what you wanted for #12, feel free to merge this approve this PR and merge it. Thanks!

**Comment by jaron-l** [comment]
> @jaron-l I've tweaked the README a bit. let me know if you're still happy with it!

Looks good to me

**Review by bergercookie — APPROVED** [review]

**Comment by bergercookie** [comment]
Merged, thanks!

**Pull request merged**
